import localFont from "next/font/local";
import { PT_Sans_Narrow } from "next/font/google";
import "./globals.css";

const deutschlander = localFont({
  src: "./assets/fonts/deutschlander.woff2",
  variable: "--font-deutschlander",
});
/* const PTSansNarrow = localFont({
  src: ["./assets/fonts/pt-sans-regular.woff2"],
}); */

const ptsans = PT_Sans_Narrow({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-ptsans",
});
export const metadata = {
  title: "Nick Walker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${ptsans.variable} ${deutschlander.variable}`}>
      <body>{children}</body>
    </html>
  );
}
