import "./globals.css";
import localFont from "next/font/local";

const deutschlander = localFont({
  src: "./assets/fonts/deutschlander.woff2",
  variable: "--font-deutschlander",
});

const ptsans = localFont({
  src: "./assets/fonts/ptsansregular.woff2",
  variable: "--font-ptsans",
});

export const metadata = {
  title: "Walker Nation - Nick Walker",
  description: "Generated by create next app",
};

/* const ptsans = PT_Sans_Narrow({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-ptsans",
}); */

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ptsans.variable} ${deutschlander.variable}`}>
        {children}
      </body>
    </html>
  );
}
