import localFont from "next/font/local";
import { PT_Sans_Narrow } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Walker Nation - Nick Walker",
  description: "Generated by create next app",
};

const deutschlander = localFont({
  src: "./assets/fonts/deutschlander.woff2",
  variable: "--font-deutschlander",
});

const ptsans = PT_Sans_Narrow({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-ptsans",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${ptsans.variable} ${deutschlander.variable}`}>
      <body>{children}</body>
    </html>
  );
}
